// IPC channel names — single source of truth for both main and preload.

export const IPC = {
  ptyCreate: 'pty:create',
  ptyWrite: 'pty:write',
  ptyResize: 'pty:resize',
  ptyFlow: 'pty:flow',
  ptyKill: 'pty:kill',
  ptyDestroy: 'pty:destroy',
  ptyGenerateName: 'pty:generate-name',
  ptyGenerateGroupName: 'pty:generate-group-name',
  ptyCapture: 'pty:capture',
  ptyReadScrollback: 'pty:read-scrollback',
  ptySendText: 'pty:send-text',
  claudeReadTranscript: 'claude:read-transcript',
  chatReadTranscript: 'chat:read-transcript',
  appToggleMarkdown: 'app:toggle-markdown',
  appCloseNode: 'app:close-node',
  appCloseWindow: 'app:close-window',
  appNotify: 'app:notify',
  appFocusNode: 'app:focus-node',
  appSetBadge: 'app:set-badge',
  agentStatus: 'agent:status',
  agentSubagentActivity: 'agent:subagent-activity',
  contextLinkSetLinks: 'context-link:set-links',
  appUpdateAvailable: 'app:update-available',
  appUpdateDownloaded: 'app:update-downloaded',
  appUpdateProgress: 'app:update-progress',
  appUpdateError: 'app:update-error',
  appUpdateNotAvailable: 'app:update-not-available',
  appCheckForUpdates: 'app:check-for-updates',
  appGetVersion: 'app:get-version',
  appUserDataDir: 'app:user-data-dir',
  appUpdatePolicy: 'app:update-policy',
  licenseActivate: 'license:activate',
  licenseDeactivate: 'license:deactivate',
  licenseStatus: 'license:status',
  licenseChanged: 'license:changed',
  licenseUpgrade: 'license:upgrade',
  appRestartToUpdate: 'app:restart-to-update',
  announcementsFetch: 'announcements:fetch',
  usageFetch: 'usage:fetch',
  usageRefresh: 'usage:refresh',
  usageUpdate: 'usage:update',
  contextUpdate: 'context:update',
  contextEnsure: 'context:ensure',
  // Events broadcast from main to the renderer (sessionId is appended to the channel name).
  ptyData: (sessionId: string) => `pty:data:${sessionId}`,
  ptyExit: (sessionId: string) => `pty:exit:${sessionId}`,
  workspaceLoad: 'workspace:load',
  workspaceSave: 'workspace:save',
  dialogSelectFolder: 'dialog:select-folder',
  dialogSelectFile: 'dialog:select-file',
  shellReveal: 'shell:reveal',
  shellOpenPath: 'shell:open-path',
  fsList: 'fs:list',
  fsRead: 'fs:read',
  fsReadBinary: 'fs:read-binary',
  fsWrite: 'fs:write',
  filesQuickOpen: 'files:quick-open',
  settingsLoad: 'settings:load',
  settingsSave: 'settings:save',
  sshList: 'ssh:list',
  sshSave: 'ssh:save',
  sshDelete: 'ssh:delete',
  sshImport: 'ssh:import-candidates',
  gitStatus: 'git:status',
  gitInit: 'git:init',
  gitClone: 'git:clone',
  gitCommit: 'git:commit',
  gitPush: 'git:push',
  gitPull: 'git:pull',
  gitSync: 'git:sync',
  gitPublish: 'git:publish',
  gitStage: 'git:stage',
  gitUnstage: 'git:unstage',
  gitStageAll: 'git:stage-all',
  gitUnstageAll: 'git:unstage-all',
  gitDiff: 'git:diff',
  gitDiscard: 'git:discard',
  gitSwitchBranch: 'git:switch-branch',
  gitCreateBranch: 'git:create-branch',
  gitShowFile: 'git:show-file',
  gitHistory: 'git:history',
  gitCommitFiles: 'git:commit-files',
  gitRemoteCommitUrl: 'git:remote-commit-url',
  gitMerge: 'git:merge',
  gitRebase: 'git:rebase',
  gitDeleteBranch: 'git:delete-branch',
  gitRenameBranch: 'git:rename-branch',
  gitFetch: 'git:fetch',
  gitForcePush: 'git:force-push',
  gitStashPush: 'git:stash-push',
  gitStashPop: 'git:stash-pop',
  gitRevert: 'git:revert',
  gitBranchAt: 'git:branch-at',
  gitCheckoutCommit: 'git:checkout-commit',
  gitRepoRoot: 'git:repo-root',
  gitWorktreeList: 'git:worktree-list',
  gitWorktreeAdd: 'git:worktree-add',
  gitWorktreeMerge: 'git:worktree-merge',
  gitWorktreeRemove: 'git:worktree-remove',
  shellOpenExternal: 'shell:open-external',
  commitGenerate: 'commit:generate',
  remoteHostStart: 'remote:host:start',
  remoteHostStop: 'remote:host:stop',
  // Connection approval gate: main → renderer when a client finishes the handshake (carries the
  // SAS to display); renderer → main to approve/reject. Until approved, the host serves no
  // pty/fs RPCs or input frames, so a leaked offer cannot grant silent access.
  remoteHostPeerPending: 'remote:host:peer-pending',
  remoteHostApprove: 'remote:host:approve',
  remoteHostReject: 'remote:host:reject',
  // Host canvas mirror: renderer pushes its serialized active-project canvas to main;
  // main pushes a client's mutation back to the host renderer to apply.
  remoteHostCanvasState: 'remote:host:canvas-state',
  remoteHostApplyMutation: 'remote:host:apply-mutation',
  // Remote-access CLIENT (drives a host's PTYs over the relay).
  remoteClientConnect: 'remote:client:connect',
  remoteClientDisconnect: 'remote:client:disconnect',
  remoteClientCreate: 'remote:client:create',
  remoteClientWrite: 'remote:client:write',
  remoteClientResize: 'remote:client:resize',
  remoteClientKill: 'remote:client:kill',
  // Client canvas mirror: main pushes the host's full canvas snapshot to the client renderer;
  // the client renderer sends its local mutations back for main to RPC to the host.
  remoteClientMutate: 'remote:client:mutate',
  // Remote filesystem: the client proxies the local `fs:*` shape onto the host over the relay.
  remoteClientFsList: 'remote:client:fs-list',
  remoteClientFsRead: 'remote:client:fs-read',
  remoteClientFsReadBinary: 'remote:client:fs-read-binary',
  remoteClientFsWrite: 'remote:client:fs-write',
  // The channel SAS pushed main->renderer once the client handshake completes, so the client
  // human can compare it with the code shown on the host before the host approves.
  remoteClientSas: (connectionId: string) => `remote:client:sas:${connectionId}`,
  // Host canvas snapshot pushed main->renderer for a connection (connectionId appended).
  remoteClientCanvasState: (connectionId: string) => `remote:client:canvas-state:${connectionId}`,
  // Per-session events broadcast main->renderer (connectionId + streamId appended).
  remoteClientData: (connectionId: string, streamId: number) =>
    `remote:client:data:${connectionId}:${streamId}`,
  remoteClientExit: (connectionId: string, streamId: number) =>
    `remote:client:exit:${connectionId}:${streamId}`,
  // Fired when a connection's relay socket drops (host/relay gone).
  remoteClientClosed: (connectionId: string) => `remote:client:closed:${connectionId}`,
  handoffBuild: 'handoff:build'
} as const
