import os from 'os'
import fs from 'fs'
import path from 'path'
import { execFile, execFileSync } from 'child_process'
import { promisify } from 'util'
import { app, ipcMain, webContents } from 'electron'
import * as pty from 'node-pty'
import { IPC } from '../shared/ipc'
import {
  DEFAULT_SETTINGS,
  type PtyCreateOptions,
  type PtyCreateResult,
  type Settings
} from '../shared/types'
import { hookServer } from './agents/hook-server'
import {
  remoteTmuxHasSessionArgs,
  remoteTmuxKillArgs,
  remoteTmuxPtyArgs,
  remoteCapturePaneArgs
} from './remote-ssh/control-master'
import { TMUX_SOCKET, sessionName } from './tmux-naming'
import { writeScrollback, readScrollback, deleteScrollback } from './scrollback-store'

// How often we snapshot a live tmux session's scrollback to disk, so a machine reboot (which
// kills the tmux server) can still replay recent output on cold restart. A final snapshot also
// runs on detach; the interval covers an ungraceful power loss between detaches.
const SCROLLBACK_SNAPSHOT_MS = 15_000

// Async exec for tmux side-calls (capture / send-keys / kill-session) so they never block
// the main event loop — a synchronous capture-pane of a large scrollback would stall every
// other session's PTY streaming and all IPC for its duration.
const runAsync = promisify(execFile)

// Minimal tmux config so the user's ~/.tmux.conf never interferes. The tmux server
// (under our socket) keeps sessions alive while no client is attached, which is what
// gives us continuity across node remounts and full app restarts.
function tmuxConf(scrollback: number): string {
  return `# auto-generated by node-terminal — do not edit
set -g status off
set -g mouse on
set -g history-limit ${Math.max(1000, scrollback)}
set -g default-terminal "xterm-256color"
set -sg escape-time 10
set -g destroy-unattached off
setw -g aggressive-resize on
set -g set-clipboard on
# With mouse on, a drag in a normal-screen shell makes a tmux copy-mode selection (not an
# xterm one), so the renderer's Cmd+C can't see it. Pipe the selection straight to the macOS
# clipboard when the drag ends — so mouse-select copies like a native terminal (iTerm-style).
bind -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
# Double-click word / triple-click line also copy to the clipboard.
bind -T copy-mode    DoubleClick1Pane send-keys -X select-word \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi DoubleClick1Pane send-keys -X select-word \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode    TripleClick1Pane send-keys -X select-line \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi TripleClick1Pane send-keys -X select-line \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
`
}

/** Resolve an absolute tmux path (GUI apps don't inherit the shell PATH). */
function findTmux(): string | null {
  for (const c of ['/opt/homebrew/bin/tmux', '/usr/local/bin/tmux', '/usr/bin/tmux', '/bin/tmux']) {
    try {
      if (fs.existsSync(c)) return c
    } catch {
      // ignore
    }
  }
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v tmux'], {
      encoding: 'utf-8'
    }).trim()
    if (out) return out
  } catch {
    // ignore
  }
  return null
}

/** Resolve an absolute ssh path (GUI apps don't inherit the shell PATH). */
let cachedSsh: string | null | undefined
function findSsh(): string | null {
  if (cachedSsh !== undefined) return cachedSsh
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v ssh'], {
      encoding: 'utf-8'
    }).trim()
    cachedSsh = out || null
  } catch {
    cachedSsh = null
  }
  // Common fallback locations if the login shell lookup failed.
  if (!cachedSsh) {
    for (const p of ['/usr/bin/ssh', '/usr/local/bin/ssh', '/opt/homebrew/bin/ssh']) {
      try {
        execFileSync(p, ['-V'], { stdio: 'ignore' })
        cachedSsh = p
        break
      } catch {
        // keep trying
      }
    }
  }
  return cachedSsh ?? null
}

interface Session {
  proc: pty.IPty
  /** Renderer webContents to stream output to over IPC, or null for a detached (host) session. */
  webContentsId: number | null
  /** Detached sinks: when set, output/exit go to these callbacks instead of IPC (relay host). */
  onData?: (data: string) => void
  onExit?: (exitCode: number) => void
  /** Pending output chunks, coalesced into one IPC message per flush. */
  buf: string[]
  bufBytes: number
  flushTimer: ReturnType<typeof setTimeout> | null
  /** Node id this session persists under (when tmux-backed) — used for scrollback snapshots. */
  persistKey?: string
  /** When set, the session runs on a remote host via ssh; kill/capture target the REMOTE tmux. */
  sshRemote?: NonNullable<PtyCreateOptions['sshRemote']>
  /** Periodic scrollback-to-disk snapshot timer (tmux-backed sessions only). */
  snapshotTimer: ReturnType<typeof setInterval> | null
}

/** Sinks for a detached session whose output is served somewhere other than the renderer
 * (the relay host). The PTY is otherwise identical to a normal session. */
export interface DetachedSinks {
  onData(data: string): void
  onExit(exitCode: number): void
}

// Output coalescing: a fast producer (e.g. `yes`, a verbose build, tmux full-screen
// redraws) emits many small chunks. Buffering them for one short window collapses N
// IPC messages + N xterm writes into one, which is the single hottest path in the app.
const FLUSH_MS = 8
const MAX_BUF_BYTES = 256 * 1024

/**
 * Manages all live PTY processes and bridges them to the renderer over IPC.
 *
 * On macOS/Linux with tmux available, each terminal node attaches to a persistent
 * tmux session named after its node id (`tmux new-session -A`). Closing a node's
 * window only detaches the client — the tmux session (and everything running in it)
 * survives, so reopening the node or restarting the app reattaches and continues
 * where it left off. Without tmux, it falls back to a plain shell (no persistence).
 */
export class PtyManager {
  private sessions = new Map<string, Session>()
  private counter = 0
  private tmuxPath: string | null = null
  private confPath = ''
  private getSettings: () => Settings = () => DEFAULT_SETTINGS

  /** Must run after app is ready (needs userData path). */
  init(getSettings: () => Settings): void {
    this.getSettings = getSettings
    this.tmuxPath = findTmux()
    if (!this.tmuxPath) return
    this.confPath = path.join(app.getPath('userData'), 'tmux.conf')
    try {
      fs.writeFileSync(this.confPath, tmuxConf(getSettings().tmuxScrollback))
    } catch {
      // If we can't write the config, disable tmux and fall back to a plain shell.
      this.tmuxPath = null
      return
    }
    // The tmux server outlives the app, so it won't re-read `-f` on relaunch. Push the
    // (possibly updated) config into a running server now so new bindings apply immediately;
    // a no-op error when no server exists yet (the next session loads it fresh via `-f`).
    try {
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'source-file', this.confPath], {
        stdio: 'ignore'
      })
    } catch {
      // no server running yet — ignore
    }
  }

  /** Absolute tmux path (or null if tmux is unavailable). Used by the context-link backend. */
  getTmuxBin(): string | null {
    return this.tmuxPath
  }

  registerIpc(): void {
    ipcMain.handle(
      IPC.ptyCreate,
      (event, options: PtyCreateOptions): Promise<PtyCreateResult> =>
        this.create(event.sender.id, options)
    )
    ipcMain.on(IPC.ptyWrite, (_event, sessionId: string, data: string) =>
      this.write(sessionId, data)
    )
    ipcMain.on(IPC.ptyResize, (_event, sessionId: string, cols: number, rows: number) =>
      this.resize(sessionId, cols, rows)
    )
    ipcMain.on(IPC.ptyFlow, (_event, sessionId: string, resume: boolean) =>
      this.setFlow(sessionId, resume)
    )
    ipcMain.on(IPC.ptyKill, (_event, sessionId: string) => this.kill(sessionId))
    ipcMain.on(IPC.ptyDestroy, (_event, persistKey: string) => this.destroySession(persistKey))
    ipcMain.handle(IPC.ptyReadScrollback, (_event, persistKey: string) =>
      readScrollback(persistKey)
    )
    ipcMain.handle(IPC.ptySendText, (_event, persistKey: string, text: string) =>
      this.sendText(persistKey, text)
    )
  }

  private async create(
    webContentsId: number,
    options: PtyCreateOptions
  ): Promise<PtyCreateResult> {
    // A tmux-backed session is "fresh" (cold start) when no live session exists to reattach to
    // — i.e. first open, or after a machine reboot killed the tmux server. Plain (non-tmux)
    // sessions are always fresh: they have no cross-restart continuity. The renderer uses this
    // to decide whether to replay the persisted scrollback and re-launch a resumable agent.
    const tmuxBacked =
      !!this.tmuxPath && this.getSettings().tmuxEnabled && !!options.persistKey
    // For an SSH-project node, "fresh" is decided by the REMOTE tmux server (over the project's
    // ControlMaster), not the local one. The remote `has-session` is a full network round-trip,
    // so it MUST be async (`runAsync`) — a synchronous probe here would freeze every window/IPC
    // for its duration. Falls through to the local tmux/plain logic otherwise (a local socket
    // probe is cheap and stays synchronous).
    const fresh = options.sshRemote
      ? !(await this.remoteSessionExists(
          options.sshRemote,
          sessionName(options.persistKey as string)
        ))
      : tmuxBacked
        ? !this.tmuxSessionExists(options.persistKey as string)
        : true
    const sessionId = this.spawnSession(options, webContentsId, undefined)
    return { sessionId, fresh }
  }

  /** Does the node's remote tmux session exist (over the project's ControlMaster)? Async so the
   *  network round-trip never blocks the main event loop. */
  private async remoteSessionExists(
    sshRemote: NonNullable<PtyCreateOptions['sshRemote']>,
    sessionId: string
  ): Promise<boolean> {
    const ssh = findSsh()
    if (!ssh) return false
    try {
      await runAsync(ssh, remoteTmuxHasSessionArgs(sshRemote.conn, sshRemote.controlPath, sessionId))
      return true
    } catch {
      return false
    }
  }

  /** Find the live session registered under a node id (persistKey), if any. */
  private sessionByPersistKey(persistKey: string): Session | undefined {
    for (const session of this.sessions.values()) {
      if (session.persistKey === persistKey) return session
    }
    return undefined
  }

  /** Whether a tmux session for this node id currently exists (server alive + session present). */
  private tmuxSessionExists(persistKey: string): boolean {
    if (!this.tmuxPath) return false
    try {
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'has-session', '-t', sessionName(persistKey)], {
        stdio: 'ignore'
      })
      return true
    } catch {
      return false
    }
  }

  /**
   * Spawn a PTY whose output/exit are delivered to `sinks` instead of the renderer. Used by
   * the relay host (Task 6) to serve PTYs over the E2EE transport: the host pipes `onData`
   * into `OP.Output` frames and maps client RPC/frames back to `write`/`resize`/`kill`. The
   * spawn (tmux session, hook env, shell selection) is identical to a normal renderer session.
   */
  createDetached(options: PtyCreateOptions, sinks: DetachedSinks): string {
    return this.spawnSession(options, null, sinks)
  }

  /**
   * Attach a detached (relay-served) PTY to the EXISTING tmux session for a node id, rather
   * than always creating a fresh one. Because `spawnSession` uses `tmux new-session -A`, passing
   * the node id as the `persistKey` reattaches the existing `nt-<nodeId>` session if it exists,
   * or creates it otherwise (graceful fallback). Used by the relay host so a mirrored terminal
   * resumes the host's live session instead of opening a blank shell. Pair with `captureSnapshot`
   * to paint the current screen before live output starts streaming. Because `sinks` is set here,
   * `spawnSession` attaches WITHOUT `-D` (co-attach), so the host's own local tmux client stays
   * attached and both the host and the mirroring client view the same session simultaneously.
   */
  attachDetached(
    persistKey: string,
    sinks: DetachedSinks,
    options: Omit<PtyCreateOptions, 'persistKey'> = { cols: 80, rows: 24 }
  ): string {
    return this.spawnSession({ ...options, persistKey }, null, sinks)
  }

  /**
   * Capture the CURRENT visible pane of a node's tmux session (with colors, via `-e`). Returns
   * the screen text so the relay host can send it as a snapshot the mirrored client paints before
   * live output. Empty string if tmux is unavailable or the session doesn't exist yet.
   */
  async captureSnapshot(persistKey: string): Promise<string> {
    if (!this.tmuxPath) return ''
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-e', '-t', sessionName(persistKey)],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      return stdout
    } catch {
      return ''
    }
  }

  private spawnSession(
    options: PtyCreateOptions,
    webContentsId: number | null,
    sinks: DetachedSinks | undefined
  ): string {
    const sessionId = `pty-${++this.counter}`
    // For a remote (ssh-project) node the local PTY just holds the ssh client, so its local cwd
    // must be a real LOCAL directory (options.cwd is a REMOTE path that wouldn't exist locally and
    // would make pty.spawn throw). The remote working dir is passed to tmux via sshRemote.remoteCwd.
    const cwd = options.sshRemote ? os.homedir() : options.cwd || os.homedir()

    // Strip TMUX so tmux doesn't refuse to nest if the app itself was launched
    // from inside a tmux session.
    const env = { ...process.env, TERM: 'xterm-256color' } as Record<string, string>
    delete env.TMUX
    delete env.TMUX_PANE

    // Agent hooks: each session carries the hook-server coordinates + its node/agent id.
    // Our managed hook (installed globally in each agent's config, but a no-op without these
    // vars) then posts state back to us for any agent run in this session.
    const hookEnv = options.persistKey
      ? hookServer.buildPtyEnv(options.persistKey, options.agentId ?? 'claude')
      : {}
    for (const [k, v] of Object.entries(hookEnv)) env[k] = v

    const settings = this.getSettings()
    let file: string
    let args: string[]

    // Resolve the session program. A bare 'ssh' is resolved to an absolute path because GUI
    // apps don't inherit the shell PATH; its args come from options.shellArgs.
    const reqShell = options.shell
    const program = reqShell === 'ssh' ? findSsh() ?? 'ssh' : reqShell
    const programArgs = options.shellArgs ?? []

    // SSH project node: run `ssh -t '<remote tmux attach-or-create>'` as the PTY program. The
    // REMOTE tmux provides persistence (over the project's ControlMaster); the local PTY just
    // holds the ssh client. Only when BOTH sshRemote and persistKey are set and ssh resolves —
    // otherwise this falls through to the unchanged local-tmux / plain-shell branches below.
    const remoteSsh = options.sshRemote && options.persistKey ? findSsh() : null
    if (options.sshRemote && options.persistKey && remoteSsh) {
      file = remoteSsh
      args = remoteTmuxPtyArgs(
        options.sshRemote.conn,
        options.sshRemote.controlPath,
        sessionName(options.persistKey),
        options.sshRemote.remoteCwd,
        // An agent preset may pass a remote program to run inside the remote tmux; usually undefined.
        options.shell,
        options.shellArgs
      )
    } else if (this.tmuxPath && settings.tmuxEnabled && options.persistKey) {
      // attach-or-create the persistent session for this node.
      // `-A` = attach-or-create. `-D` = detach OTHER clients on attach. We use `-D` ONLY for the
      // local renderer client (a remount should take sole ownership of its session). A host-served
      // PTY (sinks set) MUST NOT detach others: the host's own local client is attached to the same
      // `nt-<id>` session, and a connecting client should MIRROR it (tmux co-attach), not kick it
      // off — `-D` there is exactly what showed "[detached]" in every host window on connect.
      // (tmux sizes a co-attached session to the smallest client — the accepted mirroring tradeoff.)
      // `-e` sets the session environment explicitly (the tmux server is shared, so relying
      // on the client's inherited env would leak the first session's values into later ones).
      file = this.tmuxPath
      // The hook-server env (port/token/node id/agent id) is passed explicitly via `-e`
      // (one `-e KEY=VALUE` per key) since the shared tmux server can't rely on inherited env.
      const hookEnvArgs = Object.entries(hookEnv).flatMap(([k, v]) => ['-e', `${k}=${v}`])
      const attachFlags = sinks ? ['-A'] : ['-A', '-D']
      args = [
        '-L',
        TMUX_SOCKET,
        '-f',
        this.confPath,
        'new-session',
        ...attachFlags,
        ...hookEnvArgs,
        '-c',
        cwd,
        '-s',
        sessionName(options.persistKey)
      ]
      // Honor a custom session program at creation (ignored on reattach).
      const shell = program || settings.defaultShell
      if (shell) {
        args.push(shell)
        args.push(...programArgs)
      }
    } else {
      file =
        program ||
        settings.defaultShell ||
        process.env.SHELL ||
        (os.platform() === 'win32' ? 'powershell.exe' : 'bash')
      args = program ? programArgs : []
    }

    const proc = pty.spawn(file, args, {
      name: 'xterm-256color',
      cols: options.cols,
      rows: options.rows,
      cwd,
      env
    })

    // tmux-backed sessions snapshot their scrollback to disk periodically so a machine reboot
    // (which kills the tmux server) can still replay recent output on cold restart. A remote
    // (ssh-project) node is persisted too — the snapshot is captured from the REMOTE tmux.
    // Mark the session remote ONLY when the remote branch above actually ran (`remoteSsh` resolved).
    // If ssh is missing, the node fell through to a LOCAL tmux/plain spawn, so it must NOT be
    // marked remote — otherwise destroy/capture would target a remote tmux that was never spawned
    // and silently leak the local session.
    const remote = options.sshRemote && options.persistKey && remoteSsh ? options.sshRemote : undefined
    const tmuxBacked = !!(this.tmuxPath && settings.tmuxEnabled && options.persistKey)
    const persisted = !!options.persistKey && (remote ? true : tmuxBacked)
    const session: Session = {
      proc,
      webContentsId,
      onData: sinks?.onData,
      onExit: sinks?.onExit,
      buf: [],
      bufBytes: 0,
      flushTimer: null,
      persistKey: persisted ? options.persistKey : undefined,
      sshRemote: remote,
      snapshotTimer: null
    }
    if (persisted && options.persistKey) {
      const key = options.persistKey
      session.snapshotTimer = setInterval(() => {
        void this.snapshotScrollback(key, remote)
      }, SCROLLBACK_SNAPSHOT_MS)
    }
    this.sessions.set(sessionId, session)

    proc.onData((data) => this.queueData(sessionId, session, data))

    proc.onExit(({ exitCode }) => {
      if (session.snapshotTimer) clearInterval(session.snapshotTimer)
      this.flush(sessionId, session) // deliver any buffered output before the exit signal
      if (session.onExit) {
        session.onExit(exitCode)
      } else if (webContentsId !== null) {
        this.send(webContentsId, IPC.ptyExit(sessionId), exitCode)
      }
      this.sessions.delete(sessionId)
    })

    return sessionId
  }

  /** Buffer a chunk; flush immediately past the byte cap, otherwise on a short timer. */
  private queueData(sessionId: string, session: Session, data: string): void {
    session.buf.push(data)
    session.bufBytes += data.length
    if (session.bufBytes >= MAX_BUF_BYTES) {
      this.flush(sessionId, session)
    } else if (!session.flushTimer) {
      session.flushTimer = setTimeout(() => this.flush(sessionId, session), FLUSH_MS)
    }
  }

  /** Send all buffered output for a session as a single IPC message. */
  private flush(sessionId: string, session: Session): void {
    if (session.flushTimer) {
      clearTimeout(session.flushTimer)
      session.flushTimer = null
    }
    if (session.buf.length === 0) return
    const data = session.buf.join('')
    session.buf = []
    session.bufBytes = 0
    if (session.onData) {
      session.onData(data)
    } else if (session.webContentsId !== null) {
      this.send(session.webContentsId, IPC.ptyData(sessionId), data)
    }
  }

  /**
   * Flow control: the renderer pauses us when xterm's write backlog grows past a high
   * watermark and resumes once it drains, so a flood can't grow the renderer buffer
   * without bound. node-pty pause()/resume() stops/starts reading the pty fd; the OS
   * pipe applies backpressure to the producing process.
   */
  setFlow(sessionId: string, resume: boolean): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    try {
      if (resume) session.proc.resume()
      else session.proc.pause()
    } catch {
      // pause/resume can throw if the proc already exited; ignore.
    }
  }

  write(sessionId: string, data: string): void {
    this.sessions.get(sessionId)?.proc.write(data)
  }

  resize(sessionId: string, cols: number, rows: number): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    // cols/rows must be at least 1, otherwise node-pty throws.
    session.proc.resize(Math.max(1, cols), Math.max(1, rows))
  }

  /**
   * Detach the client. With tmux this only kills our client process; the tmux
   * session keeps running so it can be reattached later.
   */
  kill(sessionId: string): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    if (session.flushTimer) clearTimeout(session.flushTimer)
    if (session.snapshotTimer) clearInterval(session.snapshotTimer)
    // Final snapshot on detach (node unmount / app quit) so the very latest scrollback survives
    // a reboot. The tmux session itself keeps running, so this only races a same-instant capture.
    if (session.persistKey) void this.snapshotScrollback(session.persistKey, session.sshRemote)
    session.proc.kill()
    this.sessions.delete(sessionId)
  }

  /**
   * Capture a session's output. `full` grabs the entire scrollback (`-S -`, for the
   * markdown view); otherwise the recent ~200 lines (AI naming, palette search).
   */
  async captureSession(persistKey: string, full = false): Promise<string> {
    // Remote (ssh-project) node: there is no local tmux session — capture from the REMOTE tmux
    // over the project's ControlMaster (mirrors snapshotScrollback / destroySession).
    const sshRemote = this.sessionByPersistKey(persistKey)?.sshRemote
    if (sshRemote) {
      const ssh = findSsh()
      if (!ssh) return ''
      try {
        const { stdout } = await runAsync(
          ssh,
          remoteCapturePaneArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey), full),
          { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
        )
        return stdout
      } catch {
        return ''
      }
    }
    if (!this.tmuxPath) return ''
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-t', sessionName(persistKey), '-S', full ? '-' : '-200'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      return stdout
    } catch {
      return ''
    }
  }

  /**
   * Snapshot a node's recent scrollback (with colors, `-e`) to disk for cold-restart replay.
   * Best-effort: a missing session / unavailable tmux just leaves the prior snapshot in place.
   */
  private async snapshotScrollback(
    persistKey: string,
    sshRemote?: NonNullable<PtyCreateOptions['sshRemote']>
  ): Promise<void> {
    if (sshRemote) {
      // Remote (ssh-project) node: capture from the REMOTE tmux over the project's ControlMaster.
      const ssh = findSsh()
      if (!ssh) return
      try {
        const { stdout } = await runAsync(
          ssh,
          remoteCapturePaneArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey), false),
          { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
        )
        if (stdout) writeScrollback(persistKey, stdout)
      } catch {
        // remote session gone / master down — keep the last good snapshot
      }
      return
    }
    if (!this.tmuxPath) return
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-e', '-t', sessionName(persistKey), '-S', '-1500'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      if (stdout) writeScrollback(persistKey, stdout)
    } catch {
      // session gone / tmux unavailable — keep the last good snapshot
    }
  }

  /**
   * Send literal text followed by Enter into a node's tmux session (e.g. a slash command).
   * Works whether or not a client is attached. Returns false if tmux is unavailable or the
   * session doesn't exist yet.
   */
  async sendText(persistKey: string, text: string): Promise<boolean> {
    if (!this.tmuxPath) return false
    const target = sessionName(persistKey)
    try {
      // The literal text and the Enter must be sent in order, so await sequentially.
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, '-l', text])
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, 'Enter'])
      return true
    } catch {
      return false
    }
  }

  /** Permanently end a node's persistent tmux session (called when the user closes it). */
  async destroySession(persistKey: string): Promise<void> {
    // The node is gone for good — drop its cold-restore snapshot too.
    deleteScrollback(persistKey)
    // destroy() is called (close button) while the session is still live, so its sshRemote is
    // known. Capture it synchronously before any await.
    const sshRemote = this.sessionByPersistKey(persistKey)?.sshRemote
    if (sshRemote) {
      // Remote (ssh-project) node: there is no local tmux session — end the REMOTE one.
      const ssh = findSsh()
      if (!ssh) return
      try {
        await runAsync(ssh, remoteTmuxKillArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey)))
      } catch {
        // remote session may not exist / master down; ignore
      }
      return
    }
    if (!this.tmuxPath) return
    try {
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'kill-session', '-t', sessionName(persistKey)])
    } catch {
      // session may not exist; ignore
    }
  }

  /**
   * On quit, detach all clients (do NOT kill tmux sessions — that's the whole point
   * of persistence). The tmux server keeps the sessions alive for next launch.
   */
  killAll(): void {
    for (const session of this.sessions.values()) {
      if (session.flushTimer) clearTimeout(session.flushTimer)
      if (session.snapshotTimer) clearInterval(session.snapshotTimer)
      // Best-effort final scrollback snapshot on quit so a reboot can replay it. Fire-and-forget:
      // the tmux server (and the snapshot capture against it) outlives this process.
      if (session.persistKey) void this.snapshotScrollback(session.persistKey, session.sshRemote)
      session.proc.kill()
    }
    this.sessions.clear()
  }

  private send(webContentsId: number, channel: string, payload: unknown): void {
    const wc = webContents.fromId(webContentsId)
    if (wc && !wc.isDestroyed()) wc.send(channel, payload)
  }
}
